name: Deploy dist to Hostinger

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push dist to deploy branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: deploy        # branch que a Hostinger vai monitorar
          FOLDER: dist          # pasta do seu repo que vai ser publicada
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Deploy: ({sha}) {msg}"